 
/home/zhaoyong/MyShell/batchReplace.sh 'contentDocIndexColumn:' 'Document Index Column'
/home/zhaoyong/MyShell/batchReplace.sh 'contentWordColumn:' 'Words Column'

/home/zhaoyong/MyShell/batchReplace.sh 'dictionarySchema:' 'Dictionary Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'dictionaryTable:' 'Dictionary Table'
/home/zhaoyong/MyShell/batchReplace.sh 'dicIndexColumn:' 'Dictionary Index Column'
/home/zhaoyong/MyShell/batchReplace.sh 'dicContentColumn:' 'Dictionary Content Column'

/home/zhaoyong/MyShell/batchReplace.sh 'PLDAModelOutputSchema:' 'Model Output Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'PLDADropIfExist:' 'Drop If Exists (Model Table)'
/home/zhaoyong/MyShell/batchReplace.sh 'PLDAModelOutputTable:' 'Model Output Table'

/home/zhaoyong/MyShell/batchReplace.sh 'Alpha:' 'Alpha'
/home/zhaoyong/MyShell/batchReplace.sh 'Beta:' 'Beta'
/home/zhaoyong/MyShell/batchReplace.sh 'iterationNumber:' 'Number of Iterations'

/home/zhaoyong/MyShell/batchReplace.sh 'topicNumber:' 'Number of Topics'
/home/zhaoyong/MyShell/batchReplace.sh 'topicOutTable:' 'Topic Output Table'
/home/zhaoyong/MyShell/batchReplace.sh 'topicOutSchema:' 'Topic Output Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'topicDropIfExist:' 'Drop If Exists (Topic)'

/home/zhaoyong/MyShell/batchReplace.sh 'docTopicOutTable:' 'Document Topic Output Table'
/home/zhaoyong/MyShell/batchReplace.sh 'docTopicOutSchema:' 'Document Topic Output Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'docTopicDropIfExist:' 'Drop If Exists (Document Topic)'

/home/zhaoyong/MyShell/batchReplace.sh 'PLDADocTopicOutputTable:' 'PLDA Document Topic Output Table'
/home/zhaoyong/MyShell/batchReplace.sh 'PLDADocTopicOutputSchema:' 'PLDA Document Topic Output Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'PLDADocTopicDropIfExist:' 'Drop If Exists (PLDA Document Topic)'


/home/zhaoyong/MyShell/batchReplace.sh 'categoryDomain:' 'Category Domain'
/home/zhaoyong/MyShell/batchReplace.sh 'IDColumn:' 'ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'threshold:' 'Threshold'
/home/zhaoyong/MyShell/batchReplace.sh 'max_generations:' 'Number of Iterations'
/home/zhaoyong/MyShell/batchReplace.sh 'set_table_join_parameters:' 'Table Join Parameters'
/home/zhaoyong/MyShell/batchReplace.sh 'distanse:' 'Distance'
/home/zhaoyong/MyShell/batchReplace.sh 'fetchsize:' 'Fetch Size'
/home/zhaoyong/MyShell/batchReplace.sh 'epsilon:' 'Epsilon'

/home/zhaoyong/MyShell/batchReplace.sh 'columnValue:' 'Value to Predict'

/home/zhaoyong/MyShell/batchReplace.sh 'originalStep:' 'Original Step'
/home/zhaoyong/MyShell/batchReplace.sh 'Post-Recommendation_Table:' 'Post-Recommendation Table'
/home/zhaoyong/MyShell/batchReplace.sh 'columnNames:' 'Column Names'
/home/zhaoyong/MyShell/batchReplace.sh 'Min:' 'Min'
/home/zhaoyong/MyShell/batchReplace.sh 'minNumIterations:' 'Minimum Iterations'
/home/zhaoyong/MyShell/batchReplace.sh 'scopeDomain:' 'Series'
/home/zhaoyong/MyShell/batchReplace.sh 'tableSizeThreshold:' 'Table Size Threshold'
/home/zhaoyong/MyShell/batchReplace.sh 'gamma:' 'Gamma(\u03b3)'
/home/zhaoyong/MyShell/batchReplace.sh 'SVM_Regression:' 'SVM Regression'
/home/zhaoyong/MyShell/batchReplace.sh 'idColumn:' 'ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'Recommendation_ID_Column:' 'Recommendation ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'forceRetrain:' 'Force Retrain'
/home/zhaoyong/MyShell/batchReplace.sh 'Below_Cohort:' 'Below Cohort'
/home/zhaoyong/MyShell/batchReplace.sh 'aggregateType:' 'Aggregation'
/home/zhaoyong/MyShell/batchReplace.sh 'dropIfExist:' 'Drop If Exists'
/home/zhaoyong/MyShell/batchReplace.sh 'Interaction_Columns_Selection:' 'Interaction Columns Selection'
/home/zhaoyong/MyShell/batchReplace.sh 'Cohorts:' 'Cohorts'
/home/zhaoyong/MyShell/batchReplace.sh 'minSupport:' 'Minimum Support'
/home/zhaoyong/MyShell/batchReplace.sh 'Variable_Selection:' 'Variable Selection'
/home/zhaoyong/MyShell/batchReplace.sh 'Execute:' 'Others'
/home/zhaoyong/MyShell/batchReplace.sh 'groupByColumn:' 'Group By'
/home/zhaoyong/MyShell/batchReplace.sh 'quantileFieldList:' 'Quantile Fields'
/home/zhaoyong/MyShell/batchReplace.sh 'keyColumnList:' 'Key Columns'
/home/zhaoyong/MyShell/batchReplace.sh 'learning_rate:' 'Learning Rate'
/home/zhaoyong/MyShell/batchReplace.sh 'SVD_Calculator:' 'SVD Calculator'
/home/zhaoyong/MyShell/batchReplace.sh 'Max_Records:' 'Maximum Records'
/home/zhaoyong/MyShell/batchReplace.sh 'keyValue:' 'Key Value'
/home/zhaoyong/MyShell/batchReplace.sh 'decay:' 'Decay?'
/home/zhaoyong/MyShell/batchReplace.sh 'local_random_seed:' 'Local Random Seed'
/home/zhaoyong/MyShell/batchReplace.sh 'whereClause:' 'Where Clause'
/home/zhaoyong/MyShell/batchReplace.sh 'Interaction_Type:' 'Interaction Type'
/home/zhaoyong/MyShell/batchReplace.sh 'degree:' 'Polynomial Degree'
/home/zhaoyong/MyShell/batchReplace.sh 'speedupConst:' 'Speed-Up Constant'
/home/zhaoyong/MyShell/batchReplace.sh 'minImprovement:' 'Minimum Improvement'
/home/zhaoyong/MyShell/batchReplace.sh 'maximal_depth:' 'Maximal Depth'
/home/zhaoyong/MyShell/batchReplace.sh 'First_Column:' 'First Column'
/home/zhaoyong/MyShell/batchReplace.sh 'Column_Filter:' 'Column Filter'
/home/zhaoyong/MyShell/batchReplace.sh 'UdependentColumn:' 'U Dependent Column'
/home/zhaoyong/MyShell/batchReplace.sh 'normalize:' 'Normalize'
/home/zhaoyong/MyShell/batchReplace.sh 'SVM_Classification:' 'SVM Classification'
/home/zhaoyong/MyShell/batchReplace.sh 'Selection_Table_Name:' 'Selection Table Name'
/home/zhaoyong/MyShell/batchReplace.sh 'Min_Product_Count:' 'Minimum Product Count'
/home/zhaoyong/MyShell/batchReplace.sh 'UmatrixDropIfExist:' 'Drop If Exists (U-Matrix)'
/home/zhaoyong/MyShell/batchReplace.sh 'slambda:' 'Lambda(\u03bb)'
/home/zhaoyong/MyShell/batchReplace.sh 'categoryType:' 'Category'
/home/zhaoyong/MyShell/batchReplace.sh 'SVM_Novelty_Detection:' 'SVM Novelty Detection'
/home/zhaoyong/MyShell/batchReplace.sh 'number_of_prepruning_alternatives:' 'Number of Prepruning Alternatives'
/home/zhaoyong/MyShell/batchReplace.sh 'outputType:' 'Output Type'
/home/zhaoyong/MyShell/batchReplace.sh 'improvementReached:' 'Improvement Reached'
/home/zhaoyong/MyShell/batchReplace.sh 'error_epsilon:' 'Error Epsilon'
/home/zhaoyong/MyShell/batchReplace.sh 'minimal_size_for_split:' 'Minimal Size For Split'
/home/zhaoyong/MyShell/batchReplace.sh 'positiveValue:' 'Positive Value'
/home/zhaoyong/MyShell/batchReplace.sh 'VmatrixTable:' 'V-Matrix Table'
/home/zhaoyong/MyShell/batchReplace.sh 'confidence:' 'Confidence'
/home/zhaoyong/MyShell/batchReplace.sh 'q:' 'MA Order'
/home/zhaoyong/MyShell/batchReplace.sh 'outputSchema:' 'Output Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'Pre-Recommendation_ID_Column:' 'Pre-Recommendation ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'VmatrixSchema:' 'V-Matrix Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'crossProduct:' 'Cross Product'
/home/zhaoyong/MyShell/batchReplace.sh 'keyColumn:' 'Key Column'
/home/zhaoyong/MyShell/batchReplace.sh 'training_cycles:' 'Training Cycles'
/home/zhaoyong/MyShell/batchReplace.sh 'Target_Cohort:' 'Target Cohort'
/home/zhaoyong/MyShell/batchReplace.sh 'samplingColumn:' 'Sampling Column'
/home/zhaoyong/MyShell/batchReplace.sh 'minimal_leaf_size:' 'Minimal Leaf Size'
/home/zhaoyong/MyShell/batchReplace.sh 'p:' 'AR Order'
/home/zhaoyong/MyShell/batchReplace.sh 'Customer_Table_name:' 'Customer Table Name'
/home/zhaoyong/MyShell/batchReplace.sh 'rangeMin:' 'Range Minimum'
/home/zhaoyong/MyShell/batchReplace.sh 'goodValue:' 'Value to Predict'
/home/zhaoyong/MyShell/batchReplace.sh 'good:' 'Value to Predict'
/home/zhaoyong/MyShell/batchReplace.sh 'minimal_gain:' 'Minimal Gain'
/home/zhaoyong/MyShell/batchReplace.sh 'Customer_ID_Column:' 'Customer ID'
/home/zhaoyong/MyShell/batchReplace.sh 'dbConnectionName:' 'DB Connection'
/home/zhaoyong/MyShell/batchReplace.sh 'no_pre_pruning:' 'No Pre-pruning'
/home/zhaoyong/MyShell/batchReplace.sh 'sampleSizeType:' 'Sample Size Type'
/home/zhaoyong/MyShell/batchReplace.sh 'Product_Recommendation:' 'Product Recommendation'
/home/zhaoyong/MyShell/batchReplace.sh 'colName:' 'Column Name'
/home/zhaoyong/MyShell/batchReplace.sh 'distance:' 'Distance'
/home/zhaoyong/MyShell/batchReplace.sh 'VmatrixDropIfExist:' 'Drop If Exists (V-Matrix)'
/home/zhaoyong/MyShell/batchReplace.sh 'split_Number:' 'Number of Splits'
/home/zhaoyong/MyShell/batchReplace.sh 'Interaction_Condition:' 'Interaction Condition'
/home/zhaoyong/MyShell/batchReplace.sh 'size_threshold_load_data:' 'Load Data Threshold'
/home/zhaoyong/MyShell/batchReplace.sh 'outputTable:' 'Output Table'
/home/zhaoyong/MyShell/batchReplace.sh 'Time_Series:' 'Time Series'
/home/zhaoyong/MyShell/batchReplace.sh 'calculateDeviance:' 'Calculate Deviance'
/home/zhaoyong/MyShell/batchReplace.sh 'nu:' 'Nu(\u03bd)'
/home/zhaoyong/MyShell/batchReplace.sh 'UMatrixTable:' 'U-Matrix Table'
/home/zhaoyong/MyShell/batchReplace.sh 'SequenceColumn:' 'Sequence Column'
/home/zhaoyong/MyShell/batchReplace.sh 'minConfidence:' 'Minimum Confidence'
/home/zhaoyong/MyShell/batchReplace.sh 'Scoring:' 'Scoring'
/home/zhaoyong/MyShell/batchReplace.sh 'slowdownConst:' 'Slowdown Constant'
/home/zhaoyong/MyShell/batchReplace.sh 'earlyTeminate:' 'Early Termination'
/home/zhaoyong/MyShell/batchReplace.sh 'max_optimization_steps:' 'Maximum Optimization Steps'
/home/zhaoyong/MyShell/batchReplace.sh 'Id_column_is_not_distinct:' 'The ID Column is not distinct.'
/home/zhaoyong/MyShell/batchReplace.sh 'fastSpeedupConst:' 'Fast Speedup Constant'
/home/zhaoyong/MyShell/batchReplace.sh 'groupByFieldList:' 'Group By'
/home/zhaoyong/MyShell/batchReplace.sh 'Duplicate:' 'Duplicate'
/home/zhaoyong/MyShell/batchReplace.sh 'Solutions:' 'Solutions'
/home/zhaoyong/MyShell/batchReplace.sh 'Score_Threshold:' 'Score Threshold'
/home/zhaoyong/MyShell/batchReplace.sh 'Second_Column:' 'Second Column'
/home/zhaoyong/MyShell/batchReplace.sh 'UfeatureColumn:' 'U Feature Column'
/home/zhaoyong/MyShell/batchReplace.sh 'adjust_per:' 'Adjust Per'
/home/zhaoyong/MyShell/batchReplace.sh 'tableName:' 'Table Name'
/home/zhaoyong/MyShell/batchReplace.sh 'valueDomain:' 'Value Domain'
/home/zhaoyong/MyShell/batchReplace.sh 'aggregateColumn:' 'Aggregate Column'
/home/zhaoyong/MyShell/batchReplace.sh 'Data_Extraction:' 'Data Extraction'
/home/zhaoyong/MyShell/batchReplace.sh 'aggregateFieldList:' 'Aggregate'
/home/zhaoyong/MyShell/batchReplace.sh 'SVM_Prediction:' 'SVM Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'kernelType:' 'Kernel Type'
/home/zhaoyong/MyShell/batchReplace.sh 'Customer_Value_Column:' 'Customer Value Column'
/home/zhaoyong/MyShell/batchReplace.sh 'numFeatures:' 'Number of Features'
/home/zhaoyong/MyShell/batchReplace.sh 'valueColumn:' 'Value Column'
/home/zhaoyong/MyShell/batchReplace.sh 'Info_gain:' 'Information Gain'
/home/zhaoyong/MyShell/batchReplace.sh 'selectedTable:' 'Selected Table'
/home/zhaoyong/MyShell/batchReplace.sh 'numIterations:' 'Number of Iterations'
/home/zhaoyong/MyShell/batchReplace.sh 'method:' 'Method'
/home/zhaoyong/MyShell/batchReplace.sh 'hidden_layers:' 'Hidden Layers'
/home/zhaoyong/MyShell/batchReplace.sh 'Product_Recommendation_Evaluation:' 'Product Recommendation Evaluation'
/home/zhaoyong/MyShell/batchReplace.sh 'Above_Cohort:' 'Above Cohort'
/home/zhaoyong/MyShell/batchReplace.sh 'fetchSize:' 'Fetch Size'
/home/zhaoyong/MyShell/batchReplace.sh 'Recommendation_Table:' 'Recommendation Table'
/home/zhaoyong/MyShell/batchReplace.sh 'VdependentColumn:' 'V Dependent Column'
/home/zhaoyong/MyShell/batchReplace.sh 'SimThreshold:' 'Sim Threshold'
/home/zhaoyong/MyShell/batchReplace.sh 'Post-Recommendation_Value_Column:' 'Post-Recommendation Value'
/home/zhaoyong/MyShell/batchReplace.sh 'fieldList:' 'Field List'
/home/zhaoyong/MyShell/batchReplace.sh 'randomSeed:' 'Random Seed'
/home/zhaoyong/MyShell/batchReplace.sh 'Pre-Recommendation_Value_Column:' 'Pre-Recommendation Value Column'
/home/zhaoyong/MyShell/batchReplace.sh 'SVD:' 'SVD'
/home/zhaoyong/MyShell/batchReplace.sh 'Group_By:' 'Group By'
/home/zhaoyong/MyShell/batchReplace.sh 'Recommendation_Product_Column:' 'Recommendation Product Column'
/home/zhaoyong/MyShell/batchReplace.sh 'replacement:' 'Replacement'
/home/zhaoyong/MyShell/batchReplace.sh 'Max:' 'Max'
/home/zhaoyong/MyShell/batchReplace.sh 'columnY:' 'Column Y'
/home/zhaoyong/MyShell/batchReplace.sh 'is_Duplicated:' 'Is Duplicated'
/home/zhaoyong/MyShell/batchReplace.sh 'columnX:' 'Column X'
/home/zhaoyong/MyShell/batchReplace.sh 'categoryColumn:' 'Category Column'
/home/zhaoyong/MyShell/batchReplace.sh 'useModel:' 'Use Model'
/home/zhaoyong/MyShell/batchReplace.sh 'max_runs:' 'Maximum Runs'
/home/zhaoyong/MyShell/batchReplace.sh 'consistent:' 'Consistent'
/home/zhaoyong/MyShell/batchReplace.sh 'SVD-Pre:' 'SVD Pre'
/home/zhaoyong/MyShell/batchReplace.sh 'interActionModel:' 'Interaction Parameters'
/home/zhaoyong/MyShell/batchReplace.sh 'sampleCount:' 'Number of Samples'
/home/zhaoyong/MyShell/batchReplace.sh 'sqlClause:' 'SQL Clause'
/home/zhaoyong/MyShell/batchReplace.sh 'randomSeed_:' 'Random Seed'
/home/zhaoyong/MyShell/batchReplace.sh 'useArray:' 'Use Array'
/home/zhaoyong/MyShell/batchReplace.sh 'Cohorts_ID:' 'Cohorts ID'
/home/zhaoyong/MyShell/batchReplace.sh 'no_pruning:' 'No Pruning'
/home/zhaoyong/MyShell/batchReplace.sh 'k:' 'K'
/home/zhaoyong/MyShell/batchReplace.sh 'dependentColumn:' 'Dependent Column'
/home/zhaoyong/MyShell/batchReplace.sh 'Info_gain_ratio:' 'Information Gain Ratio'
/home/zhaoyong/MyShell/batchReplace.sh 'TimeSeries_Prediction:' 'Time Series Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'outputTablePrefix:' 'Output Table Prefix'
/home/zhaoyong/MyShell/batchReplace.sh 'aheadNumber:' 'Ahead Number'
/home/zhaoyong/MyShell/batchReplace.sh 'columns_bins:' 'Bin Configuration'
/home/zhaoyong/MyShell/batchReplace.sh 'Pre-Recommendation_Table:' 'Pre-Recommendation Table'
/home/zhaoyong/MyShell/batchReplace.sh 'VMatrixTable:' 'V-Matrix Table'
/home/zhaoyong/MyShell/batchReplace.sh 'disjoint:' 'Disjoint'
/home/zhaoyong/MyShell/batchReplace.sh 'tableAggregation:' 'Table Aggregation'
/home/zhaoyong/MyShell/batchReplace.sh 'Id_column_cannot_be_same_as_Value_column:' 'Id column cannot be the same as the Value column'
/home/zhaoyong/MyShell/batchReplace.sh 'SQL-Execute_operator_cannot_link_without_preceding_operator.:' 'The SQL-Execute operator cannot link without preceding operator.'
/home/zhaoyong/MyShell/batchReplace.sh 'scoreType:' 'Score Type'
/home/zhaoyong/MyShell/batchReplace.sh 'ID_Column:' 'ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'Customer_Product_Column:' 'Customer Product Column'
/home/zhaoyong/MyShell/batchReplace.sh 'Selection_ID_Column:' 'Selection ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'Interaction_Columns:' 'Interaction Columns'
/home/zhaoyong/MyShell/batchReplace.sh 'schemaName:' 'Schema Name'
/home/zhaoyong/MyShell/batchReplace.sh 'eta:' 'Eta(\u03b7)'
/home/zhaoyong/MyShell/batchReplace.sh 'Load_data_Threshold:' 'Load Data Threshold'
/home/zhaoyong/MyShell/batchReplace.sh 'rangeMax:' 'Maximum Range'
/home/zhaoyong/MyShell/batchReplace.sh 'windowFieldList:' 'Window Field List'
/home/zhaoyong/MyShell/batchReplace.sh 'SQL-Execute:' 'SQL-Execute'
/home/zhaoyong/MyShell/batchReplace.sh 'UmatrixTable:' 'U-Matrix Table'
/home/zhaoyong/MyShell/batchReplace.sh 'initValue:' 'Initial Value'
/home/zhaoyong/MyShell/batchReplace.sh 'modifyOriginTable:' 'Modify Original Table'
/home/zhaoyong/MyShell/batchReplace.sh 'Edit_Interaction_Columns:' 'Edit Interaction Columns'
/home/zhaoyong/MyShell/batchReplace.sh 'rowName:' 'Row Name'
/home/zhaoyong/MyShell/batchReplace.sh 'Customer_Product_Count_Column:' 'Customer Product Count Column'
/home/zhaoyong/MyShell/batchReplace.sh 'Transformed_info_gain:' 'Transformed Information Gain'
/home/zhaoyong/MyShell/batchReplace.sh 'momentum:' 'Momentum'
/home/zhaoyong/MyShell/batchReplace.sh 'UmatrixSchema:' 'U-Matrix Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'Post-Recommendation_Product_Column:' 'Post-Recommendation Product Column'
/home/zhaoyong/MyShell/batchReplace.sh 'Filter_Text_Configuration:' 'Filter Text Configuration'
/home/zhaoyong/MyShell/batchReplace.sh 'Filter_Text:' 'Filter Text'
/home/zhaoyong/MyShell/batchReplace.sh 'sampleSize:' 'Sample Size'
/home/zhaoyong/MyShell/batchReplace.sh 'd:' 'Degree Of Differencing'
/home/zhaoyong/MyShell/batchReplace.sh 'createSequenceID:' 'Create Sequence ID'
/home/zhaoyong/MyShell/batchReplace.sh 'SVD_Prediction:' 'SVD Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'Post-Recommendation_ID_Column:' 'Post-Recommendation ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'pivotColumn:' 'Pivot Column'
/home/zhaoyong/MyShell/batchReplace.sh 'VfeatureColumn:' 'V Feature Column'
/home/zhaoyong/MyShell/batchReplace.sh 'adaboostUIModel:' 'Model Parameter Settings'
/home/zhaoyong/MyShell/batchReplace.sh 'groupColumn:' 'Group Column'
/home/zhaoyong/MyShell/batchReplace.sh 'expression:' 'Expression'
/home/zhaoyong/MyShell/batchReplace.sh 'singularValueSchema:' 'Singular Table Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'singularValueTable:' 'Singular Table'
/home/zhaoyong/MyShell/batchReplace.sh 'singularValueDropIfExist:' 'Drop If Exists (Singular)'
/home/zhaoyong/MyShell/batchReplace.sh 'rowNameF:' 'Row Name'
/home/zhaoyong/MyShell/batchReplace.sh 'colNameF:' 'Column Name'
/home/zhaoyong/MyShell/batchReplace.sh 'UmatrixTableF:' 'U-Matrix Table'
/home/zhaoyong/MyShell/batchReplace.sh 'VmatrixTableF:' 'V-Matrix Table'
/home/zhaoyong/MyShell/batchReplace.sh 'singularValueTableF:' 'Singular Value Table'
/home/zhaoyong/MyShell/batchReplace.sh 'UdependentColumnF:' 'U Dependent Column'
/home/zhaoyong/MyShell/batchReplace.sh 'VdependentColumnF:' 'V Dependent Column'
/home/zhaoyong/MyShell/batchReplace.sh 'singularValuedependentColumnF:' 'Singular Dependent Column'
/home/zhaoyong/MyShell/batchReplace.sh 'singularValuefeatureColumn:' 'Singular Feature Column'
/home/zhaoyong/MyShell/batchReplace.sh 'isStepWise:' 'Stepwise Feature Selection'
/home/zhaoyong/MyShell/batchReplace.sh 'stepWiseType:' 'Stepwise Type'
/home/zhaoyong/MyShell/batchReplace.sh 'criterionType:' 'Criterion Type'
/home/zhaoyong/MyShell/batchReplace.sh 'checkValue:' 'Check Value'
/home/zhaoyong/MyShell/batchReplace.sh 'customerTable:' 'Customer Table Name'
/home/zhaoyong/MyShell/batchReplace.sh 'customerIDColumn:' 'Customer ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'customerValueColumn:' 'Customer Value Column'
/home/zhaoyong/MyShell/batchReplace.sh 'customerProductColumn:' 'Customer Product Column'
/home/zhaoyong/MyShell/batchReplace.sh 'customerProductCountColumn:' 'Customer Product Count Column'
/home/zhaoyong/MyShell/batchReplace.sh 'selectionTable:' 'Selection Table Name'
/home/zhaoyong/MyShell/batchReplace.sh 'selectionIDColumn:' 'Selection ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'simThreshold:' 'Sim Threshold'
/home/zhaoyong/MyShell/batchReplace.sh 'maxRecords:' 'Max Records'
/home/zhaoyong/MyShell/batchReplace.sh 'minProductCount:' 'Minimum Product Count'
/home/zhaoyong/MyShell/batchReplace.sh 'scoreThreshold:' 'Score Threshold'
/home/zhaoyong/MyShell/batchReplace.sh 'cohorts:' 'Cohorts'
/home/zhaoyong/MyShell/batchReplace.sh 'targetCohort:' 'Target Cohort'
/home/zhaoyong/MyShell/batchReplace.sh 'cohortsAbove:' 'Cohorts Above'
/home/zhaoyong/MyShell/batchReplace.sh 'cohortsBelow:' 'Cohorts Below'
/home/zhaoyong/MyShell/batchReplace.sh 'recommendationTable:' 'Recommendation Table'
/home/zhaoyong/MyShell/batchReplace.sh 'recommendationIdColumn:' 'Recommendation ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'recommendationProductColumn:' 'Recommendation Product Column'
/home/zhaoyong/MyShell/batchReplace.sh 'preTable:' 'Pre-Recommendation Table'
/home/zhaoyong/MyShell/batchReplace.sh 'preIdColumn:' 'Pre-Recommendation ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'preValueColumn:' 'Pre-Recommendation Value Column'
/home/zhaoyong/MyShell/batchReplace.sh 'postTable:' 'Post Recommendation Table'
/home/zhaoyong/MyShell/batchReplace.sh 'postIdColumn:' 'Post-Recommendation ID Column'
/home/zhaoyong/MyShell/batchReplace.sh 'postProductColumn:' 'Post-Recommendation Product Column'
/home/zhaoyong/MyShell/batchReplace.sh 'postValueColumn:' 'Post-Recommendation Value Column'
/home/zhaoyong/MyShell/batchReplace.sh 'analysisType:' 'Analysis Type'
/home/zhaoyong/MyShell/batchReplace.sh 'percent:' 'Percent'
/home/zhaoyong/MyShell/batchReplace.sh 'PCAQoutputSchema:' 'Result Output Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'PCAQoutputTable:' 'Result Output Table'
/home/zhaoyong/MyShell/batchReplace.sh 'PCAQDropIfExist:' 'Drop If Exists (Result)'
/home/zhaoyong/MyShell/batchReplace.sh 'PCAQvalueOutputSchema:' 'Eigenvalues Output Schema'
/home/zhaoyong/MyShell/batchReplace.sh 'PCAQvalueOutputTable:' 'Eigenvalues Output Table'
/home/zhaoyong/MyShell/batchReplace.sh 'PCAQvalueDropIfExist:' 'Drop If Exists (Eigenvalues)'
/home/zhaoyong/MyShell/batchReplace.sh 'remainColumns:' 'Carryover Columns'
/home/zhaoyong/MyShell/batchReplace.sh 'replacementNull:' 'Replace Null Columns'
/home/zhaoyong/MyShell/batchReplace.sh 'WOETableInfor:' 'WOE Settings'
/home/zhaoyong/MyShell/batchReplace.sh 'columnNamesMapping:' 'Column Names Mapping'
/home/zhaoyong/MyShell/batchReplace.sh 'useridIndex:' 'User ID Column Index'
/home/zhaoyong/MyShell/batchReplace.sh 'productIndex:' 'Product Column Index'
/home/zhaoyong/MyShell/batchReplace.sh 'timeIndex:' 'Time Column Index'
/home/zhaoyong/MyShell/batchReplace.sh 'productCountPerUserThreshold:' 'Product Count Per User Threshold'
/home/zhaoyong/MyShell/batchReplace.sh 'cooccurenceThreshold:' ''
/home/zhaoyong/MyShell/batchReplace.sh 'delimiter:' 'Delimiter'
/home/zhaoyong/MyShell/batchReplace.sh 'interval:' 'Minimal Interval'
/home/zhaoyong/MyShell/batchReplace.sh 'outputDir:' 'Output Directory'
/home/zhaoyong/MyShell/batchReplace.sh 'hadoopConnetionName:' 'Hadoop Connection Name'
/home/zhaoyong/MyShell/batchReplace.sh 'hadoopFileName:' 'Haddoop File Name'
/home/zhaoyong/MyShell/batchReplace.sh 'analysisValueDomain:' 'Value'
/home/zhaoyong/MyShell/batchReplace.sh 'seriesDomain:' 'Domain'
/home/zhaoyong/MyShell/batchReplace.sh 'typeDomain:' 'Group By'

/home/zhaoyong/MyShell/batchReplace.sh 'EDIT_OPERATOR:' 'Edit Operator'
/home/zhaoyong/MyShell/batchReplace.sh 'SVD_OPERATOR:' 'SVD'
/home/zhaoyong/MyShell/batchReplace.sh 'KS_OPERATOR:' 'KS'
/home/zhaoyong/MyShell/batchReplace.sh 'SVM_REGRESSION_OPERATOR:' 'SVM Regression'
/home/zhaoyong/MyShell/batchReplace.sh 'K_MEANS_OPERATOR:' 'K-Means'
/home/zhaoyong/MyShell/batchReplace.sh 'UNIVARIATE_OPERATOR:' 'Univariate Operator'
/home/zhaoyong/MyShell/batchReplace.sh 'INFORMATION_VA_OPERATOR:' 'Information Value Analysis'
/home/zhaoyong/MyShell/batchReplace.sh 'PRODUCT_RECOMMONDATION_OPERATOR:' 'Product Recommendation'
/home/zhaoyong/MyShell/batchReplace.sh 'LINEAR_REGRESSION_OPERATOR:' 'Linear Regression'
/home/zhaoyong/MyShell/batchReplace.sh 'GINI_OPERATOR:' 'GINI'
/home/zhaoyong/MyShell/batchReplace.sh 'SVM_CLASSIFICATION_OPERATOR:' 'SVM Classification'
/home/zhaoyong/MyShell/batchReplace.sh 'DESICION_TREE_OPERATOR:' 'Decision Tree'
/home/zhaoyong/MyShell/batchReplace.sh 'NAIVE_BAYES_OPERATOR:' 'Naive Bayes'
/home/zhaoyong/MyShell/batchReplace.sh 'PIVOT_OPERATOR:' 'Pivot'
/home/zhaoyong/MyShell/batchReplace.sh 'CART_TREE_OPERATOR:' 'Cart Tree'
/home/zhaoyong/MyShell/batchReplace.sh 'ASSOCIATION_OPERATOR:' 'Association'
/home/zhaoyong/MyShell/batchReplace.sh 'LIFT_OPERATOR:' 'LIFT'
/home/zhaoyong/MyShell/batchReplace.sh 'TIME_SERIES_OPERATOR:' 'Time Series'
/home/zhaoyong/MyShell/batchReplace.sh 'CLEAR_TEMPTABLEANDWIEW_OPERATOR:' 'Operator'
/home/zhaoyong/MyShell/batchReplace.sh 'SQLEXECUTE_OPERATOR:' 'SQL-Execute'
/home/zhaoyong/MyShell/batchReplace.sh 'CORRELATION_ANALYSIS_OPERATOR:' 'Correlation Analysis'
/home/zhaoyong/MyShell/batchReplace.sh 'REMOVE_OPERATOR:' 'Remove Operator'
/home/zhaoyong/MyShell/batchReplace.sh 'GOODNESSOFFIT_OPERATOR:' 'Goodness Of Fit'
/home/zhaoyong/MyShell/batchReplace.sh 'DB_TABLE_ANALYSIS_OPERATOR:' 'Bar Chart Preview'
/home/zhaoyong/MyShell/batchReplace.sh 'ROC_OPERATOR:' 'ROC'
/home/zhaoyong/MyShell/batchReplace.sh 'MODEL_OPERATOR:' 'Model'
/home/zhaoyong/MyShell/batchReplace.sh 'VARIABLE_OPERATOR:' 'Variable'
/home/zhaoyong/MyShell/batchReplace.sh 'VARIABLE_SELECTION_OPERATOR:' 'Variable Selection'
/home/zhaoyong/MyShell/batchReplace.sh 'CUSTOMIZE_OPERATOR:' 'Customized Operator'
/home/zhaoyong/MyShell/batchReplace.sh 'NORMALIZATION_OPERATOR:' 'Normalization'
/home/zhaoyong/MyShell/batchReplace.sh 'FIELD_SELECTOR_OPERATOR:' 'Field Selector'
/home/zhaoyong/MyShell/batchReplace.sh 'PRODUCT_RECOMMONDATION_EVALUATION_OPERATOR:' 'Product Recommendation Evaluation'
/home/zhaoyong/MyShell/batchReplace.sh 'AGGREGATE_OPERATOR:' 'Aggregate'
/home/zhaoyong/MyShell/batchReplace.sh 'NEURAL_NETWORK_OPERATOR:' 'Neural Network'
/home/zhaoyong/MyShell/batchReplace.sh 'INTEGERTOTEXT_OPERATOR:' 'Numeric to Text'
/home/zhaoyong/MyShell/batchReplace.sh 'HISTOGRAM_OPERATOR:' 'Histogram Analysis'
/home/zhaoyong/MyShell/batchReplace.sh 'SCATTERMATRIX_OPERATOR:' 'Scatter Plot Matrix'
/home/zhaoyong/MyShell/batchReplace.sh 'LOGICSTIC_REGRESSION_OPERATOR:' 'Logistic Regression'
/home/zhaoyong/MyShell/batchReplace.sh 'REPLACENULL_OPERATOR:' 'Null Value Replacement'
/home/zhaoyong/MyShell/batchReplace.sh 'ERROR_CONFIGURE_OPERATOR:' ':please configure the operator before add the link.'
/home/zhaoyong/MyShell/batchReplace.sh 'DUPLICATE_OPERATOR:' 'Duplicate Operator'
/home/zhaoyong/MyShell/batchReplace.sh 'SVM_NOVELTY_DETECTION_OPERATOR:' 'SVM Novelty Detection'
/home/zhaoyong/MyShell/batchReplace.sh 'SQLEXECUTE_HAVE_NO_PRECEDING_OPERATOR:' 'SQL-Execute operator cannot link without preceding operator.'
/home/zhaoyong/MyShell/batchReplace.sh 'RENAME_OPERATOR:' 'Rename Operator'
/home/zhaoyong/MyShell/batchReplace.sh 'COLUMN_FILTER_OPERATOR:' 'Column Filter'
/home/zhaoyong/MyShell/batchReplace.sh 'DBTABLE_OPERATOR:' 'DB Table'
/home/zhaoyong/MyShell/batchReplace.sh 'TABLEJOIN_OPERATOR:' 'Table Join'
/home/zhaoyong/MyShell/batchReplace.sh 'ROWFILTER_OPERATOR:' 'Row Filter'
/home/zhaoyong/MyShell/batchReplace.sh 'COLUMNFILTER_OPERATOR:' 'Column Filter'
/home/zhaoyong/MyShell/batchReplace.sh 'N2T_OPERATOR:' 'Numeric to Text'
/home/zhaoyong/MyShell/batchReplace.sh 'BARCHART_OPERATOR:' 'Bar Chart Preview'
/home/zhaoyong/MyShell/batchReplace.sh 'CORRELATION_OPERATOR:' 'Correlation Analysis'
/home/zhaoyong/MyShell/batchReplace.sh 'FREQUENCY_OPERATOR:' 'Frequency Analysis'
/home/zhaoyong/MyShell/batchReplace.sh 'INFORMATIONVALUE_OPERATOR:' 'Information Value Analysis'
/home/zhaoyong/MyShell/batchReplace.sh 'VALUEANALYSIS_OPERATOR:' 'Value Analysis'
/home/zhaoyong/MyShell/batchReplace.sh 'NORMALIZATION_OPERATOR:' 'Normalization'
/home/zhaoyong/MyShell/batchReplace.sh 'ASSOCIATION_PREDICTION_OPERATOR:' 'Association Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'KMEANS_OPERATOR:' 'K-Means'
/home/zhaoyong/MyShell/batchReplace.sh 'DTREE_OPERATOR:' 'Decision Tree'
/home/zhaoyong/MyShell/batchReplace.sh 'CTREE_OPERATOR:' 'Cart Tree'
/home/zhaoyong/MyShell/batchReplace.sh 'TREE_PREDICT_OPERATOR:' 'Tree Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'LINEARREGRESSION_OPERATOR:' 'Linear Regression'
/home/zhaoyong/MyShell/batchReplace.sh 'LINEARREGRESSION_PREDICT_OPERATOR:' 'Linear Regression Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'LOGISTICREGRESSION_OPERATOR:' 'Logistic Regression'
/home/zhaoyong/MyShell/batchReplace.sh 'LOGISTICREGRESSION_PREDICT_OPERATOR:' 'Logistic Regression Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'NAIVE_BAYES_PREDICTION_OPERATOR:' 'Naive Bayes Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'NEURAL_NETWORK_PREDICTION_OPERATOR:' 'Neural Network Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'RANDOM_SAMPLING_OPERATOR:' 'Random Sampling'
/home/zhaoyong/MyShell/batchReplace.sh 'SAMPLE_SELECTOR_OPERATOR:' 'Sample Selector'
/home/zhaoyong/MyShell/batchReplace.sh 'STRATIFIED_SAMPLING_OPERATOR:' 'Stratified Sampling'
/home/zhaoyong/MyShell/batchReplace.sh 'SVM_PREDICTION:' 'SVM Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'TIMESERIES_OPERATOR:' 'Time Series'
/home/zhaoyong/MyShell/batchReplace.sh 'TIMESERIES_PREDICTION_OPERATOR:' 'TimeSeries Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'UNIVARIATEEXPLORER_OPERATOR:' 'Univariate Explorer'
/home/zhaoyong/MyShell/batchReplace.sh 'SCATTERPLOT_OPERATOR:' 'Scatter Plot'
/home/zhaoyong/MyShell/batchReplace.sh 'BOXANDWISKER_OPERATOR:' 'Box And Whisker'

/home/zhaoyong/MyShell/batchReplace.sh 'SVD_OPERATOR:' 'SVD'
/home/zhaoyong/MyShell/batchReplace.sh 'SVD_CALCULATOR:' 'SVD Calculator'

/home/zhaoyong/MyShell/batchReplace.sh 'ADABOOST_OPERATOR:' 'AdaBoost'
/home/zhaoyong/MyShell/batchReplace.sh 'ADABOOST_PREDICTION_OPERATOR:' 'AdaBoost Prediction'
/home/zhaoyong/MyShell/batchReplace.sh 'PCA_OPERATOR:' 'Principal Component Analysis'
/home/zhaoyong/MyShell/batchReplace.sh 'WOE_OPERATOR:' 'Weight of Evidence'
/home/zhaoyong/MyShell/batchReplace.sh 'WOE_TABLE_GENERATOR_OPERATOR:' 'WOE Table Generator'

/home/zhaoyong/MyShell/batchReplace.sh '                                     :' ''
/home/zhaoyong/MyShell/batchReplace.sh 'SQLEXECUTE_HAVE_NO_PRECEDING_OPERATOR:' 'The SQL-Execute operator cannot link without a preceding operator.'
/home/zhaoyong/MyShell/batchReplace.sh 'MESSAGE_CHECK_LINK:' 'Invalid link : Cannot link from "{0}" to "{1}".'
/home/zhaoyong/MyShell/batchReplace.sh 'MESSAGE_ALREADY_LINK:' 'Link already created.'
/home/zhaoyong/MyShell/batchReplace.sh 'CANT_LINK_MUTIL_DATASOURCE:' 'Cannot link more than one data source to "{0}".'
/home/zhaoyong/MyShell/batchReplace.sh 'CAN_NOT_LINK_MUTIL_MODEL:' 'Cannot link more than one model to "{0}".'
/home/zhaoyong/MyShell/batchReplace.sh 'CANNOT_LINKMUTIL_TOOPERATOR:' 'Cannot link more than one input to "{0}".                                 '
/home/zhaoyong/MyShell/batchReplace.sh 'SVDC_CHECK_LINK_SVD_EXISTS:' '{0} is linked; cannot link {1}'
/home/zhaoyong/MyShell/batchReplace.sh 'ERROR_Configure_Operator:' ':please configure the operator before adding the link.'
/home/zhaoyong/MyShell/batchReplace.sh 'SUBFLOW_INVALID:' 'parameters are not valid:'
/home/zhaoyong/MyShell/batchReplace.sh 'SUBFLOW_OR:' 'or'

/home/zhaoyong/MyShell/batchReplace.sh 'TABLESET_OPERATOR:' 'Table Set'
/home/zhaoyong/MyShell/batchReplace.sh 'tableSetConfig:' 'Table Set Configuration'

/home/zhaoyong/MyShell/batchReplace.sh 'univariateModel:' 'Column Names'

/home/zhaoyong/MyShell/batchReplace.sh 'PLDA_OPERATOR:' 'PLDA Trainer'
/home/zhaoyong/MyShell/batchReplace.sh 'PLDA_OPERATOR_SHORT:' 'PLDA Trainer'

/home/zhaoyong/MyShell/batchReplace.sh 'PLDA_PREDICT_OPERATOR:' 'PLDA Predictor'
/home/zhaoyong/MyShell/batchReplace.sh 'PLDA_PREDICT_OPERATOR_SHORT:' 'PLDA Predictor'

/home/zhaoyong/MyShell/batchReplace.sh 'StorageParameters:' 'Storage Parameters'

/home/zhaoyong/MyShell/batchReplace.sh 'UmatrixTableStorageParameters:' 'U-Matrix Table Storage Parameters'
/home/zhaoyong/MyShell/batchReplace.sh 'VmatrixTableStorageParameters:' 'V-Matrix Table Storage Parameters'
/home/zhaoyong/MyShell/batchReplace.sh 'singularValueTableStorageParameters:' 'Singular Value Table Storage Parameters'
/home/zhaoyong/MyShell/batchReplace.sh 'PCAQoutputTableStorageParameters:' 'Result Output Table Storage Parameters'
/home/zhaoyong/MyShell/batchReplace.sh 'PCAQvalueOutputTableStorageParameters:' 'Eigenvalues Output Table Storage Parameters'
/home/zhaoyong/MyShell/batchReplace.sh 'PLDADocTopicOutputTableStorageParameters:' 'Document Topic Output Table Storage Parameters'
/home/zhaoyong/MyShell/batchReplace.sh 'PLDAModelOutputTableStorageParameters:' 'Model Output Table Storage Parameters'
/home/zhaoyong/MyShell/batchReplace.sh 'docTopicOutTableStorageParameters:' 'Document Topic Output Table Storage Parameters'
/home/zhaoyong/MyShell/batchReplace.sh 'topicOutTableStorageParameters:' 'Topic Output Table Storage Parameters '

/home/zhaoyong/MyShell/batchReplace.sh 'SUBFLOW_OPERATOR:' 'Sub-Flow'


/home/zhaoyong/MyShell/batchReplace.sh 'subflowPath:' 'Sub-Flow '
/home/zhaoyong/MyShell/batchReplace.sh 'tableMapping:' 'Input Table Mapping'
/home/zhaoyong/MyShell/batchReplace.sh 'exitOperator:' 'Exit Operator'
/home/zhaoyong/MyShell/batchReplace.sh 'subflowVariable:' 'Sub-Flow Variable'

/home/zhaoyong/MyShell/batchReplace.sh 'HP_FILE_OPERATOR:' 'Hadoop File'
/home/zhaoyong/MyShell/batchReplace.sh 'HP_FILE_OPERATOR_SHORT:' 'Hadoop File'
/home/zhaoyong/MyShell/batchReplace.sh 'HP_PR_OPERATOR:' 'Hadoop Product Recommendation'
/home/zhaoyong/MyShell/batchReplace.sh 'HP_PR_OPERATOR_SHORT:' 'Hadoop Product Recommendation'

/home/zhaoyong/MyShell/batchReplace.sh 'TABLE_ALREADY_LINK:' 'Table is already linked.'
